#!/bin/bash

# Install Nix packages from config.nix, including stow
nix-env -iA nixpkgs.myPackages

# Use stow to create symlinks
cd ~/dotfiles

# Stow each directory

# Additional specific stow commands for individual files
stow tmux
stow zsh
stow bat
stow yazi
