#!/bin/bash

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

nix-env -iA nixpkgs.myPackages

# Verify stow installation
if ! command -v stow &> /dev/null
then
    echo "Stow could not be found. Please check your Nix configuration."
    exit 1
fi

# Use stow to create symlinks
cd "$(HOME)/dotfiles"

stow tmux
stow zsh
stow bat
stow nvim
stow yazi
