#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME/nixpkgs"

# Link the config.nix file to the Nix configuration directory
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME/nixpkgs/config.nix"

# Install Nix packages from config.nix
nix-shell "$XDG_CONFIG_HOME/nixpkgs/config.nix" --run "echo 'Nix environment set up'"

# Verify stow installation
if ! command -v stow &> /dev/null
then
    echo "Stow could not be found. Please check your Nix configuration."
    exit 1
fi

# Use stow to create symlinks
cd "$PWD"

stow -t "$HOME" tmux
stow -t "$HOME" zsh
stow -t "$XDG_CONFIG_HOME" bat
stow -t "$XDG_CONFIG_HOME" nvim
stow -t "$XDG_CONFIG_HOME" yazi
